### PR TITLE
Added Sentinel-2 masking

### PR DESCRIPTION
**Pull request by fangfy**
Additional Sentinel-2 masking to remove pixels with values of 1 in either red or nir band, which leads to incorrect NDVI. 

Tested for the Mali patch and the tile. Suggest run another month in dev to confirm results are otherwise the same.

### CODE REVIEW

**Comment by lisarebelo** [comment]
Looks good to me. Agree with suggested way forward, can we run another month and do some final checks to make sure there are no other issues.

**Review by SeffatChowdhury — APPROVED** [review]

**Comment by fangfy** [comment]
Will also be good to confirm this doesn't increase much the cost of the production.

**Comment by SeffatChowdhury** [comment]
@fangfy sorry I missed this earlier. The only way I can definitively answer this is to do a small dev run and time it. Will still be approximate though.

**Comment by lisarebelo** [comment]
@SeffatChowdhury I think that is fine. We were proposing to rerun for July and August 2022 so that we can make sure there are no further artifacts.

**Comment by SeffatChowdhury** [comment]
@fangfy and @lisarebelo the current dev run doesn't seem be to be any slower than the previous runs before the update. Just a note, if any of you try a run, you need to use image-tag "latest" instead of "0.0.8"

**Comment by SeffatChowdhury** [comment]
@fangfy and @lisarebelo please have a look at Jul/Aug 2022 in dev which were produced using the updated code

**Pull request merged**
